apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-workspace
  labels:
    app: camel-integration-demo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
