apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: slack-bookings
    app.kubernetes.io/runtime: camel
  name: slack-bookings
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: slack-bookings
  type: ClusterIP
